[project]
name = "skillmatcher"
version = "0.1.0"
description = "SkillMatcher Django backend"
requires-python = ">=3.10"
dependencies = []

[tool.poetry.dependencies]
python = ">=3.10"
Django = "*"
gunicorn = "*"
djangorestframework = "*"
django-cors-headers = "*"
